# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b660a649f3872eca786f7321c00b24959926d3eb782442014c9cd3c072091b2c6190c2a3052be4b12b6183b60096bed30a24f5194d7c4ba8b19b58111434b7a

test:
  secret_key_base: af7d432160534c380628b6a0795fcd9e3076c084b1ec349a783b8a1cc305b7ed1fd4d3204a8ba5ea9b2dee2bbd362b457475c362c8d69042380fa84e247a51ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
